---
# tasks file for nginx
- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Config nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
