---
- name: copy config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: nginx_template.conf.j2, dest: /etc/nginx/conf.d/proxy_kodcloud.oldboyedu.com.conf }
    - { src: proxy_params.j2, dest: /etc/nginx/proxy_params }
  notify: Restart nginx
  when: is_proxy
  vars:
    server_name: kodcloud.oldboyedu.com

- name: create ssl directory
  file:
    path: '{{ ssl_key_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0644'
  when: is_https

- name: copy key-crt
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: server.key, dest: /etc/nginx/ssl_key/server.key }
    - { src: server.crt, dest: /etc/nginx/ssl_key/server.crt }
  notify: Restart nginx
  when: is_https

- name: Create code dir
  file:
    path: '{{ codes }}/kodcloud'
    state: directory
    recurse: yes
    owner: '{{ public_user }}'
    group: '{{ public_group }}'
    mode: '0755'
  when: is_web

- name: Copy code
  unarchive:
    src: kodexplorer4.40.zip
    dest: '{{ codes }}/kodcloud'
    owner: '{{ public_user }}'
    group: '{{ public_group }}'
    copy: yes
    creates: '{{ codes }}/kodcloud/index.php'
  when: is_php_site

- name: copy config file
  template:
    src: nginx_template.conf.j2
    dest: /etc/nginx/conf.d/web_kodcloud.oldboyede.com.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx
  when: is_php_site
  vars:
    server_name: kodcloud.oldboyedu.com
    code_path: /code/kodcloud/

- name: Configure NFS Mount
  mount:
    src: "{{ nfs_ip }}:{{ nfs_kodcloud_dir }}"
    path: /code/kodcloud/data
    fstype: nfs
    opts: defaults
    state: mounted
  when: is_web
