---
# tasks file for php
- name: install php
  yum:
    name: "{{ packages }}"
    state: present
    enablerepo: remi-php71
  when: is_php

- name: Config php
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: php.ini.j2, dest: /etc/php.ini, owner: root, group: root, mode: '0644' }
    - { src: www.conf.j2, dest: /etc/php-fpm.d/www.conf, owner: root, group: root, mode: '0644' }
  notify: Restart php
  when: is_php

- name: Start php
  systemd:
    name: php-fpm
    state: started
    enabled: yes
  when: is_php
